tasks:
  - name: open tasklist
    command: code tasklist.md
  - name: install reqs and start test
    init: pip3 install -r requirements.txt
    command: pytest-watch

vscode:
  extensions:
    - mechatroner.rainbow-csv
    - ms-python.python
    - yzhang.markdown-all-in-one
    - eamodio.gitlens
    - lextudio.restructuredtext
    - ritwickdey.liveserver
  