tasks:
  - name: open tasklist
    command: code tasklist.md mob-programming.md
  - name: install reqs and start test
    init: pip3 install -r requirements.txt
    command: pytest-watch test_validate.py

vscode:
  extensions:
    - mechatroner.rainbow-csv
  